spring.application.name=psicogest

# ==========================================
# DATABASE
# ==========================================

spring.datasource.url=jdbc:postgresql://localhost:5432/psicogest

spring.datasource.username=postgres

spring.datasource.password=1234

spring.datasource.driver-class-name=org.postgresql.Driver


# ==========================================
# JPA / HIBERNATE
# ==========================================

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# FLYWAY
# ==========================================
spring.flyway.locations=classpath:bd/migration
spring.flyway.baseline-on-migrate=true

# ==========================================
# SECURITY
# ==========================================
app.security.allowed-origins=${SECURITY_ALLOWED_ORIGINS:http://localhost:5173}

app.security.jwt.issuer=psicogest-api
app.security.jwt.audience=psicogest-web

app.security.jwt.access-token-ttl=PT10M
app.security.jwt.refresh-token-ttl=P14D

app.security.jwt.public-key=${JWT_PUBLIC_KEY_LOCATION:file:./secrets/jwt-public.pem}
app.security.jwt.private-key=${JWT_PRIVATE_KEY_LOCATION:file:./secrets/jwt-private.pem}

app.security.jwt.key-id=${JWT_KEY_ID:primary-2026}

app.security.jwt.refresh-cookie-name=psicogest_rt
app.security.jwt.secure-cookie=${JWT_COOKIE_SECURE:false}

app.security.mfa.challenge-ttl=PT5M
app.security.mfa.max-attempts=5
app.security.mfa.issuer=PsicoGest

app.security.mfa.encryption-key=${MFA_ENCRYPTION_KEY}

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}

# LOGIN

app.security.rate-limit.login-ip.capacity=30
app.security.rate-limit.login-ip.refill-period=PT5M

app.security.rate-limit.login-account.capacity=10
app.security.rate-limit.login-account.refill-period=PT15M


# REFRESH

app.security.rate-limit.refresh-ip.capacity=120
app.security.rate-limit.refresh-ip.refill-period=PT1M


# MFA

app.security.rate-limit.mfa-ip.capacity=30
app.security.rate-limit.mfa-ip.refill-period=PT5M

app.security.rate-limit.mfa-challenge.capacity=8
app.security.rate-limit.mfa-challenge.refill-period=PT5M
