import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { ClipboardList, FileClock, LockKeyhole, Search, ShieldCheck } from "lucide-react";
import { dataSource } from "../../shared/lib/mock-api";
import { formatDateTime } from "../../shared/lib/format";
import { Button, Card, EmptyState, Notice, PageHeader, Skeleton, StatusBadge } from "../../shared/components/ui";

export function ClinicalRecordsPage() {
  const patients = useQuery({ queryKey: ["patients"], queryFn: dataSource.getPatients });
  const records = useQuery({ queryKey: ["clinical-records"], queryFn: async () => { const all = await dataSource.getPatients(); const entries = await Promise.all(all.map(async (patient) => ({ patient, records: await dataSource.getRecords(patient.id) }))); return entries.flatMap(({ patient, records: patientRecords }) => patientRecords.map((record) => ({ record, patient }))); } });
  return <div><PageHeader eyebrow="Clínica / Registros" title="Prontuários clínicos" description="Lista operacional com acesso contextual; o conteúdo completo permanece protegido no detalhe." actions={<Button variant="secondary"><Search size={16} /> Buscar registro</Button>} /><div className="mb-6"><Notice title="Separação clínica ativa"><span className="inline-flex items-center gap-1"><ShieldCheck size={14} /> Apenas membros com vínculo terapêutico e permissão de leitura devem visualizar o conteúdo no backend.</span></Notice></div><Card className="overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 p-5 dark:border-slate-800"><div><h2 className="font-display text-lg font-bold text-ink dark:text-white">Registros recentes</h2><p className="mt-1 text-sm text-slate-500">{patients.data?.length ?? "—"} pacientes · conteúdo minimizado nesta lista.</p></div><span className="rounded-xl bg-slate-100 p-2 text-slate-500 dark:bg-slate-800"><LockKeyhole size={18} /></span></div>{records.isPending ? <div className="space-y-3 p-5"><Skeleton className="h-16" /><Skeleton className="h-16" /></div> : records.data?.length ? <div className="divide-y divide-slate-100 dark:divide-slate-800">{records.data.map(({ record, patient }) => <div key={record.id} className="grid gap-3 p-5 md:grid-cols-[1.3fr_1fr_140px_120px] md:items-center"><div className="flex items-center gap-3"><span className="rounded-xl bg-sage-50 p-2 text-sage-700 dark:bg-sage-950/40 dark:text-sage-300"><ClipboardList size={17} /></span><div><Link to={`/patients/${patient.id}/clinical-record`} className="text-sm font-bold text-ink hover:text-sage-700 dark:text-white dark:hover:text-sage-300">{patient.name}</Link><p className="mt-1 text-xs text-slate-500">{record.title} · conteúdo oculto na listagem</p></div></div><p className="flex items-center gap-1 text-xs text-slate-500"><FileClock size={14} /> {formatDateTime(record.updatedAt)}</p><p className="text-xs text-slate-500">{record.revisionCount} revisões · {record.addendumCount} addenda</p><div className="md:text-right"><StatusBadge value={record.state} /></div></div>)}</div> : <div className="p-5"><EmptyState title="Nenhum prontuário" description="Os registros clínicos aparecerão quando forem criados com autorização." /></div>}</Card></div>;
}
