import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { ClipboardList, FileClock, LockKeyhole, Search, ShieldCheck } from "lucide-react";
import { dataSource } from "../../shared/lib/app-api";
import { formatDateTime } from "../../shared/lib/format";
import { Button, Card, EmptyState, Input, Notice, PageHeader, Skeleton, StatusBadge } from "../../shared/components/ui";

export function ClinicalRecordsPage() {
  const [query, setQuery] = useState("");
  const patients = useQuery({ queryKey: ["patients"], queryFn: dataSource.getPatients });
  const records = useQuery({ queryKey: ["clinical-records"], queryFn: async () => { const all = await dataSource.getPatients(); const entries = await Promise.all(all.map(async (patient) => ({ patient, records: await dataSource.getRecords(patient.id) }))); return entries.flatMap(({ patient, records: patientRecords }) => patientRecords.map((record) => ({ record, patient }))); } });
  const filteredRecords = useMemo(() => {
    const normalizedQuery = query.trim().toLowerCase();
    return (records.data ?? []).filter(({ patient, record }) => !normalizedQuery || `${patient.name} ${record.title}`.toLowerCase().includes(normalizedQuery));
  }, [query, records.data]);

  return <div><PageHeader eyebrow="Clínica / Registros" title="Prontuários clínicos" description="Lista operacional com acesso contextual; o conteúdo completo permanece protegido no detalhe." actions={<div className="w-full sm:w-72"><Input aria-label="Buscar registro" placeholder="Buscar paciente ou registro…" value={query} onChange={(event) => setQuery(event.target.value)} leadingIcon={<Search size={16} />} /></div>} /><div className="mb-6"><Notice title="Separação clínica ativa"><span className="inline-flex items-center gap-1"><ShieldCheck size={14} /> Apenas membros com vínculo terapêutico e permissão de leitura devem visualizar o conteúdo no backend.</span></Notice></div><Card className="overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 p-5 dark:border-slate-800"><div><h2 className="font-display text-lg font-bold text-ink dark:text-white">Registros recentes</h2><p className="mt-1 text-sm text-slate-500">{patients.data?.length ?? "—"} pacientes · conteúdo minimizado nesta lista.</p></div><span className="rounded-xl bg-slate-100 p-2 text-slate-500 dark:bg-slate-800"><LockKeyhole size={18} /></span></div>{records.isPending ? <div className="space-y-3 p-5"><Skeleton className="h-16" /><Skeleton className="h-16" /></div> : records.isError ? <div className="p-5"><EmptyState title="Registros indisponíveis" description="Não foi possível consultar os prontuários agora." action={<Button onClick={() => records.refetch()}>Tentar novamente</Button>} /></div> : filteredRecords.length ? <div className="divide-y divide-slate-100 dark:divide-slate-800">{filteredRecords.map(({ record, patient }) => <div key={record.id} className="grid gap-3 p-5 md:grid-cols-[1.3fr_1fr_140px_120px] md:items-center"><div className="flex items-center gap-3"><span className="rounded-xl bg-sage-50 p-2 text-sage-700 dark:bg-sage-950/40 dark:text-sage-300"><ClipboardList size={17} /></span><div><Link to={`/patients/${patient.id}/clinical-record`} className="text-sm font-bold text-ink hover:text-sage-700 dark:text-white dark:hover:text-sage-300">{patient.name}</Link><p className="mt-1 text-xs text-slate-500">{record.title} · conteúdo oculto na listagem</p></div></div><p className="flex items-center gap-1 text-xs text-slate-500"><FileClock size={14} /> {formatDateTime(record.updatedAt)}</p><p className="text-xs text-slate-500">{record.revisionCount} revisões · {record.addendumCount} addenda</p><div className="md:text-right"><StatusBadge value={record.state} /></div></div>)}</div> : <div className="p-5"><EmptyState title={query ? "Nenhum registro encontrado" : "Nenhum prontuário"} description={query ? "Tente buscar por outro paciente ou título." : "Os registros clínicos aparecerão quando forem criados com autorização."} /></div>}</Card></div>;
}
