-- Minimal pre-V12 users schema for isolated authentication tests.
-- This is not a replacement for the application's missing V1-V3 migrations.
CREATE TYPE userrole AS ENUM ('PATIENT', 'PSYCHOANALYST', 'CLINIC_ADMIN', 'SYSTEM_ADMIN');
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role userrole NOT NULL,
    active BOOLEAN NOT NULL,
    deactivated_at TIMESTAMP,
    deactivation_reason VARCHAR(255),
    reactivated_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);
