package com.psicogest.psicogest.security.audit;

public enum AuditAction {

    PATIENT_PROFILE_READ,
    PATIENT_CREATED,
    PATIENT_UPDATED,
    PATIENT_DEACTIVATED,

    APPOINTMENT_CREATED,
    APPOINTMENT_READ,
    APPOINTMENT_CONFIRMED,
    APPOINTMENT_COMPLETED,
    APPOINTMENT_CANCELLED,
    APPOINTMENT_RESCHEDULED,

    THERAPEUTIC_RELATIONSHIP_CREATED,
    THERAPEUTIC_RELATIONSHIP_SUSPENDED,
    THERAPEUTIC_RELATIONSHIP_RESUMED,
    THERAPEUTIC_RELATIONSHIP_ENDED,

    MEDICAL_RECORD_CREATED,
    MEDICAL_RECORD_READ,
    MEDICAL_RECORD_UPDATED,
    MEDICAL_RECORD_FINALIZED,
    MEDICAL_RECORD_REVISION_CREATED,
    MEDICAL_RECORD_REVISION_READ,
    MEDICAL_RECORD_ADDENDUM_CREATED,
    MEDICAL_RECORD_ADDENDUM_READ,
    CLINICAL_TIMELINE_READ,
    CLINICAL_EXPORT_REQUESTED,
    CLINICAL_EXPORT_COMPLETED,
    CLINICAL_EXPORT_DOWNLOADED,
    MEDICAL_RECORD_EXPORTED,

    /**
     * 31. Eventos financeiros (auditoria de transações)
     * 
     * Metadados incluem: amount, currency, paymentMethod
     * 
     * NUNCA auditar:
     * - Dados completos de cartão ❌
     * - CVV ❌
     * - Token de pagamento ❌
     * - Chave privada/provider secret ❌
     */
    RECEIVABLE_CREATED,
    RECEIVABLE_CANCELLED,

    PAYMENT_CREATED,
    PAYMENT_CONFIRMED,
    PAYMENT_FAILED,
    PAYMENT_CANCELLED,

    PAYMENT_ALLOCATED,

    REFUND_REQUESTED,
    REFUND_CONFIRMED,
    REFUND_FAILED,
    REFUND_CANCELLED,

    CREDIT_CREATED,
    CREDIT_APPLIED,

    INVOICE_ISSUED,
    INVOICE_CANCELLED,

    CONSENT_ACCEPTED,
    CONSENT_REVOKED,

    DATA_EXPORTED,

    /**
     * 32. Eventos de reconciliação bancária
     * 
     * Metadados: fileHash, parser type, transaction count, import count
     */
    BANK_STATEMENT_IMPORTED,
    BANK_STATEMENT_IMPORT_FAILED,

    /**
     * 33. Eventos de reconciliação manual de lançamentos
     * 
     * BANK_TRANSACTION_RECONCILED: alocação resultou em 100%
     * BANK_TRANSACTION_PARTIALLY_RECONCILED: alocação resultou em < 100%
     * BANK_TRANSACTION_IGNORED: marcado para ignorar (tarifa, juros, etc)
     * BANK_RECONCILIATION_REVERSED: reverter alocação
     */
    BANK_TRANSACTION_RECONCILED,
    BANK_TRANSACTION_PARTIALLY_RECONCILED,
    BANK_TRANSACTION_IGNORED,
    BANK_RECONCILIATION_REVERSED
}
