package com.psicogest.psicogest.security.audit;

public enum AuditAction {

    PATIENT_PROFILE_READ,
    PATIENT_CREATED,
    PATIENT_UPDATED,
    PATIENT_DEACTIVATED,

    APPOINTMENT_CREATED,
    APPOINTMENT_READ,
    APPOINTMENT_CONFIRMED,
    APPOINTMENT_COMPLETED,
    APPOINTMENT_CANCELLED,
    APPOINTMENT_RESCHEDULED,

    THERAPEUTIC_RELATIONSHIP_CREATED,
    THERAPEUTIC_RELATIONSHIP_SUSPENDED,
    THERAPEUTIC_RELATIONSHIP_RESUMED,
    THERAPEUTIC_RELATIONSHIP_ENDED,

    MEDICAL_RECORD_CREATED,
    MEDICAL_RECORD_READ,
    MEDICAL_RECORD_UPDATED,
    MEDICAL_RECORD_FINALIZED,
    MEDICAL_RECORD_ADDENDUM_CREATED,
    MEDICAL_RECORD_EXPORTED,

    PAYMENT_CREATED,
    PAYMENT_REFUNDED,

    INVOICE_ISSUED,
    INVOICE_CANCELLED,

    CONSENT_ACCEPTED,
    CONSENT_REVOKED,

    DATA_EXPORTED
}
