package com.psicogest.psicogest.security.audit;

public enum AuditAction {

    PATIENT_PROFILE_READ,
    PATIENT_CREATED,
    PATIENT_UPDATED,
    PATIENT_DEACTIVATED,

    APPOINTMENT_CREATED,
    APPOINTMENT_READ,
    APPOINTMENT_CONFIRMED,
    APPOINTMENT_COMPLETED,
    APPOINTMENT_CANCELLED,
    APPOINTMENT_RESCHEDULED,

    THERAPEUTIC_RELATIONSHIP_CREATED,
    THERAPEUTIC_RELATIONSHIP_SUSPENDED,
    THERAPEUTIC_RELATIONSHIP_RESUMED,
    THERAPEUTIC_RELATIONSHIP_ENDED,

    MEDICAL_RECORD_CREATED,
    MEDICAL_RECORD_READ,
    MEDICAL_RECORD_UPDATED,
    MEDICAL_RECORD_FINALIZED,
    MEDICAL_RECORD_REVISION_CREATED,
    MEDICAL_RECORD_REVISION_READ,
    MEDICAL_RECORD_ADDENDUM_CREATED,
    MEDICAL_RECORD_ADDENDUM_READ,
    CLINICAL_TIMELINE_READ,
    CLINICAL_EXPORT_REQUESTED,
    CLINICAL_EXPORT_COMPLETED,
    CLINICAL_EXPORT_DOWNLOADED,
    MEDICAL_RECORD_EXPORTED,

    /**
     * 31. Eventos financeiros (auditoria de transações)
     * 
     * Metadados incluem: amount, currency, paymentMethod
     * 
     * NUNCA auditar:
     * - Dados completos de cartão ❌
     * - CVV ❌
     * - Token de pagamento ❌
     * - Chave privada/provider secret ❌
     */
    RECEIVABLE_CREATED,
    RECEIVABLE_CANCELLED,

    PAYMENT_CREATED,
    PAYMENT_CONFIRMED,
    PAYMENT_FAILED,
    PAYMENT_CANCELLED,

    PAYMENT_ALLOCATED,

    REFUND_REQUESTED,
    REFUND_CONFIRMED,
    REFUND_FAILED,
    REFUND_CANCELLED,

    CREDIT_CREATED,
    CREDIT_APPLIED,

    INVOICE_ISSUED,
    INVOICE_CANCELLED,

    CONSENT_ACCEPTED,
    CONSENT_REVOKED,

    DATA_EXPORTED,

    /**
     * 32. Eventos de reconciliação bancária
     * 
     * Metadados: fileHash, parser type, transaction count, import count
     */
    BANK_STATEMENT_IMPORTED,
    BANK_STATEMENT_IMPORT_FAILED,

    /**
     * 33. Eventos de reconciliação manual de lançamentos
     * 
     * BANK_TRANSACTION_RECONCILED: alocação resultou em 100%
     * BANK_TRANSACTION_PARTIALLY_RECONCILED: alocação resultou em < 100%
     * BANK_TRANSACTION_IGNORED: marcado para ignorar (tarifa, juros, etc)
     * BANK_RECONCILIATION_REVERSED: reverter alocação
     */
    BANK_TRANSACTION_RECONCILED,
    BANK_TRANSACTION_PARTIALLY_RECONCILED,
    BANK_TRANSACTION_IGNORED,
    BANK_RECONCILIATION_REVERSED,

    /**
     * 34. Eventos de repasse de gateway (settlements)
     * 
     * PROVIDER_SETTLEMENT_RECEIVED: repasse recebido
     * PROVIDER_SETTLEMENT_VALIDATED: saldo validado e bateu
     * PROVIDER_SETTLEMENT_MISMATCH_DETECTED: divergência encontrada
     * PROVIDER_SETTLEMENT_SETTLED: gateway confirmou pagamento
     * PROVIDER_SETTLEMENT_RECONCILED: lançamento bancário reconciliado
     */
    PROVIDER_SETTLEMENT_RECEIVED,
    PROVIDER_SETTLEMENT_VALIDATED,
    PROVIDER_SETTLEMENT_MISMATCH_DETECTED,
    PROVIDER_SETTLEMENT_SETTLED,
    PROVIDER_SETTLEMENT_RECONCILED,

    /**
     * 35. Eventos de integração fiscal NFS-e
     * 
     * Metadados:
     * - IDs (não credenciais, certificados, XML completo)
     * - Códigos e hashes
     * - Timestamps e status transitions
     * 
     * NUNCA auditar:
     * - Certificado ❌
     * - Credenciais ❌
     * - Private key ❌
     * - XML fiscal completo ❌
     * - CPF completo ❌
     * - Justificativa completa (usar hash/resumo) ❌
     */
    FISCAL_ISSUER_CREATED,
    FISCAL_CONFIGURATION_CREATED,
    SERVICE_INVOICE_CREATED,
    SERVICE_INVOICE_UPDATED,
    SERVICE_INVOICE_ISSUE_REQUESTED,
    SERVICE_INVOICE_AUTHORIZED,
    SERVICE_INVOICE_REJECTED,
    SERVICE_INVOICE_RECONCILIATION_REQUIRED,
    SERVICE_INVOICE_READ,
    SERVICE_INVOICE_CANCEL_REQUESTED,
    SERVICE_INVOICE_CANCELLED,
    SERVICE_INVOICE_SUBSTITUTION_REQUESTED,
    SERVICE_INVOICE_SUBSTITUTED,
    FISCAL_DOCUMENT_DOWNLOADED,
    FISCAL_MANUAL_TAX_OVERRIDE,

    /**
     * 36. Eventos de pacotes de sessão
     * 
     * Metadados:
     * - packageId, patientId, packagePlanId
     * - sessionCount, grantedSessions
     * - purchasePrice
     */
    PACKAGE_PLAN_CREATED,
    PACKAGE_PLAN_VERSION_PUBLISHED,
    PATIENT_PACKAGE_PURCHASED,
    PATIENT_PACKAGE_ACTIVATION_TRIGGERED,
    PATIENT_PACKAGE_ACTIVATED,
    PACKAGE_SESSION_CREDIT_GRANTED,
    PACKAGE_SESSION_CONSUMED,
    PACKAGE_SESSION_CONSUMPTION_REVERSED,
    PATIENT_PACKAGE_EXPIRED,
    PATIENT_PACKAGE_CANCELLATION_PREVIEWED,
    PATIENT_PACKAGE_CANCELLATION_REQUESTED,
    PATIENT_PACKAGE_FINANCIAL_ADJUSTMENT_CREATED,
    PATIENT_PACKAGE_CREDIT_SETTLEMENT_CREATED,
    PATIENT_PACKAGE_REFUND_SETTLEMENT_CREATED,
    PATIENT_PACKAGE_CANCELLATION_COMPLETED,
    PATIENT_PACKAGE_CANCELLATION_FAILED,
    PATIENT_PACKAGE_CANCELLED,
    PACKAGE_CREDIT_MANUAL_ADJUSTMENT

    ,SUBSCRIPTION_CREATED
    ,SUBSCRIPTION_CYCLE_CREATED
    ,SUBSCRIPTION_RECEIVABLE_CREATED
    ,SUBSCRIPTION_CHARGE_REQUESTED
    ,SUBSCRIPTION_CHARGE_CONFIRMED
    ,SUBSCRIPTION_CHARGE_FAILED
    ,SUBSCRIPTION_ENTITLEMENT_GRANTED
    ,SUBSCRIPTION_PAST_DUE
    ,SUBSCRIPTION_PAUSED
    ,SUBSCRIPTION_RESUMED
    ,SUBSCRIPTION_CANCELLATION_REQUESTED
    ,SUBSCRIPTION_CANCELLED
}
