import { useState } from "react";
import { Building2, Check, Clock3, Link2, Save, Settings2, UsersRound } from "lucide-react";
import { Button, Card, Input, Notice, PageHeader, Select } from "../../shared/components/ui";
import { useToast } from "../../shared/providers/ToastProvider";

type SettingsTab = "organization" | "access" | "providers" | "quiet";
export function SettingsPage() {
  const [tab, setTab] = useState<SettingsTab>("organization");
  const toast = useToast();
  const items: { id: SettingsTab; label: string; icon: React.ReactNode }[] = [{ id: "organization", label: "Organização", icon: <Building2 size={16} /> }, { id: "access", label: "Equipe e permissões", icon: <UsersRound size={16} /> }, { id: "providers", label: "Provedores", icon: <Link2 size={16} /> }, { id: "quiet", label: "Quiet hours", icon: <Clock3 size={16} /> }];
  return <div><PageHeader eyebrow="Governança / Configurações" title="Configurações" description="Preferências do tenant com escopo explícito e segredos mantidos no backend." actions={<Button onClick={() => toast("Configurações salvas com trilha de auditoria.")}><Save size={16} /> Salvar alterações</Button>} /><div className="grid gap-6 lg:grid-cols-[230px_1fr]"><Card className="h-fit p-2"><nav aria-label="Configurações" className="space-y-1">{items.map((item) => <button key={item.id} onClick={() => setTab(item.id)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm font-bold ${tab === item.id ? "bg-sage-50 text-sage-700 dark:bg-sage-950/40 dark:text-sage-200" : "text-slate-500 hover:bg-slate-100 dark:hover:bg-slate-800"}`}>{item.icon}{item.label}</button>)}</nav></Card><Card className="p-6">{tab === "organization" && <Organization />}{tab === "access" && <Access toast={toast} />}{tab === "providers" && <Providers toast={toast} />}{tab === "quiet" && <QuietHours />}</Card></div></div>;
}

function Organization() { return <div><SettingsTitle icon={<Building2 />} title="Organização" description="Identidade e contexto da entidade financeira atual." /><div className="mt-6 grid gap-4 sm:grid-cols-2"><Input label="Nome da clínica" defaultValue="Clínica Horizonte" /><Input label="Documento" defaultValue="CNPJ ••.•••.•••/0001-••" disabled /><Select label="Fuso horário" defaultValue="America/Sao_Paulo"><option value="America/Sao_Paulo">(GMT-03:00) São Paulo</option><option value="America/Manaus">(GMT-04:00) Manaus</option></Select><Input label="E-mail operacional" defaultValue="op•••@clinicahorizonte.com" /></div><Notice title="Tenant-aware" tone="success">Configurações, provedores e regras de horário são isolados por entidade financeira.</Notice></div>; }
function Access({ toast }: { toast: (message: string) => void }) { return <div><SettingsTitle icon={<UsersRound />} title="Equipe e permissões" description="Acesso mínimo necessário, com separação clínica, administrativa e financeira." /><div className="mt-6 overflow-hidden rounded-xl border border-slate-100 dark:border-slate-800"><div className="grid grid-cols-[1.5fr_1fr_120px] gap-3 bg-slate-50 p-3 text-xs font-bold uppercase tracking-wider text-slate-400 dark:bg-slate-800/70"><span>Pessoa</span><span>Contexto</span><span>Status</span></div>{[{ name: "Helena Costa", email: "he•••@clinicahorizonte.com", role: "Administradora" }, { name: "André Lima", email: "an•••@clinicahorizonte.com", role: "Equipe clínica" }, { name: "Paula Reis", email: "pa•••@clinicahorizonte.com", role: "Financeiro" }].map((member) => <div key={member.name} className="grid grid-cols-[1.5fr_1fr_120px] gap-3 border-t border-slate-100 p-3 text-sm dark:border-slate-800"><div><p className="font-bold text-ink dark:text-white">{member.name}</p><p className="mt-1 text-xs text-slate-500">{member.email}</p></div><p className="text-slate-500">{member.role}</p><div><span className="inline-flex items-center gap-1 text-xs font-bold text-emerald-600"><Check size={14} /> Ativo</span></div></div>)}</div><Button variant="secondary" className="mt-5" onClick={() => toast("Convite de membro preparado.")}><UsersRound size={15} /> Convidar membro</Button></div>; }
function Providers({ toast }: { toast: (message: string) => void }) { return <div><SettingsTitle icon={<Link2 />} title="Provedores de notificação" description="As credenciais ficam no backend e nunca são persistidas no navegador." /><div className="mt-6 space-y-4"><ProviderRow name="WhatsApp Cloud API" scope="Clínica Horizonte · operacional" status="Conectado" onClick={() => toast("Configuração do WhatsApp aberta.")} /><ProviderRow name="E-mail transacional" scope="Domínio clinicahorizonte.com" status="Conectado" onClick={() => toast("Configuração do e-mail aberta.")} /><ProviderRow name="SMS fallback" scope="Não configurado" status="Opcional" onClick={() => toast("Fluxo de configuração iniciado.")} /></div><Notice title="Proteção de custos">Rate limits outbound são aplicados por canal, entidade financeira e plano antes do envio.</Notice></div>; }
function ProviderRow({ name, scope, status, onClick }: { name: string; scope: string; status: string; onClick: () => void }) { return <div className="flex flex-col gap-3 rounded-2xl border border-slate-100 p-4 sm:flex-row sm:items-center sm:justify-between dark:border-slate-800"><div className="flex items-center gap-3"><div className="rounded-xl bg-sage-50 p-2.5 text-sage-700 dark:bg-sage-950/40 dark:text-sage-300"><Link2 size={18} /></div><div><p className="text-sm font-bold text-ink dark:text-white">{name}</p><p className="mt-1 text-xs text-slate-500">{scope}</p></div></div><div className="flex items-center gap-3"><span className="text-xs font-bold text-emerald-600">{status}</span><Button variant="secondary" className="min-h-9 px-3 text-xs" onClick={onClick}><Settings2 size={14} /> Gerenciar</Button></div></div>; }
function QuietHours() { return <div><SettingsTitle icon={<Clock3 />} title="Quiet hours" description="Evite lembretes financeiros em horários inadequados, respeitando o fuso da clínica." /><div className="mt-6 grid gap-4 sm:grid-cols-2"><Input label="Início do silêncio" type="time" defaultValue="21:00" /><Input label="Fim do silêncio" type="time" defaultValue="08:00" /><Select label="Aplicar a" defaultValue="all"><option value="all">Todos os canais operacionais</option><option value="financial">Somente financeiros</option></Select><Select label="Fuso da entidade" defaultValue="America/Sao_Paulo"><option value="America/Sao_Paulo">America/Sao_Paulo</option></Select></div><Notice title="Exceções transacionais">Lembretes de consulta e comunicações necessárias seguem a política do tenant, mas o backend deve decidir a exceção final.</Notice></div>; }
function SettingsTitle({ icon, title, description }: { icon: React.ReactNode; title: string; description: string }) { return <div className="flex items-start gap-3"><div className="rounded-xl bg-sage-50 p-2.5 text-sage-700 dark:bg-sage-950/40 dark:text-sage-300">{icon}</div><div><h2 className="font-display text-lg font-bold text-ink dark:text-white">{title}</h2><p className="mt-1 text-sm text-slate-500">{description}</p></div></div>; }
