package com.psicogest.psicogest.model.enums;

public enum ClinicalTimelineEventType {

    APPOINTMENT_COMPLETED,

    MEDICAL_RECORD_CREATED,

    MEDICAL_RECORD_FINALIZED,

    MEDICAL_RECORD_ADDENDUM_CREATED,

    THERAPEUTIC_RELATIONSHIP_STARTED,

    THERAPEUTIC_RELATIONSHIP_SUSPENDED,

    THERAPEUTIC_RELATIONSHIP_RESUMED,

    THERAPEUTIC_RELATIONSHIP_ENDED
}