package com.psicogest.psicogest.model.enums;

public enum NotificationType {

    APPOINTMENT_CREATED,

    APPOINTMENT_CONFIRMED,

    APPOINTMENT_REMINDER,

    APPOINTMENT_RESCHEDULED,

    APPOINTMENT_CANCELLED,

    PAYMENT_CONFIRMED,

    PAYMENT_REMINDER,

    RECEIVABLE_OVERDUE,

    PACKAGE_ACTIVATED,

    PACKAGE_EXPIRING,

    PACKAGE_EXPIRED,

    SUBSCRIPTION_PAYMENT_FAILED,

    SUBSCRIPTION_PAST_DUE,

    SUBSCRIPTION_CANCELLED,

    SERVICE_INVOICE_AUTHORIZED,

    SERVICE_INVOICE_CANCELLED
}