package com.psicogest.psicogest.model.enums;

public enum SecurityIncidentCategory {
    AUTHENTICATION_FAILURE,
    AUTHORIZATION_FAILURE,
    DATA_EXFILTRATION,
    UNAUTHORIZED_ACCESS,
    MALWARE_DETECTION,
    SUSPICIOUS_ACTIVITY,
    CONFIGURATION_CHANGE,
    POLICY_VIOLATION,
    NETWORK_ANOMALY,
    SYSTEM_ANOMALY,
    CRYPTOGRAPHIC_FAILURE,
    DATA_INTEGRITY_FAILURE,
    THIRD_PARTY_COMPROMISE,
    UNKNOWN
}
