package com.psicogest.psicogest.model.enums;

public enum SecurityAlertType {
    BRUTE_FORCE_ATTEMPT,
    CREDENTIAL_STUFFING,
    UNUSUAL_LOGIN_LOCATION,
    UNUSUAL_LOGIN_TIME,
    FAILED_MFA,
    RATE_LIMIT_EXCEEDED,
    UNAUTHORIZED_ACCESS_ATTEMPT,
    PERMISSION_ESCALATION,
    DATA_EXFILTRATION_SUSPICION,
    SUSPICIOUS_DATA_ACCESS,
    MALWARE_DETECTION,
    CONFIGURATION_CHANGE,
    POLICY_VIOLATION,
    NETWORK_ANOMALY,
    SYSTEM_ANOMALY,
    CRYPTOGRAPHIC_FAILURE,
    DATA_INTEGRITY_FAILURE,
    SESSION_HIJACKING,
    TOKEN_MISUSE,
    UNKNOWN
}
