import { useState, type ReactNode } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { Laptop2, LockKeyhole, LogOut, ShieldCheck, UserRound } from "lucide-react";
import { useAuth } from "../auth/AuthContext";
import { roleLabels } from "../../shared/lib/permissions";
import type { UserRole } from "../../shared/types/domain";
import { Badge, Button, Card, Input, Notice, PageHeader, StatusBadge } from "../../shared/components/ui";
import { useToast } from "../../shared/providers/ToastProvider";
import { apiClient } from "../../shared/lib/api-client";
import { formatDateTime, maskContact } from "../../shared/lib/format";

const demoProfiles: Record<UserRole, { name: string; initials: string; summary: string; access: string[] }> = {
  OWNER: { name: "Helena Costa", initials: "HC", summary: "Visão completa da clínica, equipe, financeiro e governança.", access: ["Dashboard e indicadores", "Agenda, pacientes e prontuários", "Financeiro, fiscal e configurações"] },
  CLINICAL: { name: "André Lima", initials: "AL", summary: "Acesso focado no cuidado, agenda e registros clínicos autorizados.", access: ["Agenda e pacientes", "Prontuários e revisões", "Sem acesso a valores financeiros"] },
  ADMIN: { name: "Marina Alves", initials: "MA", summary: "Rotina administrativa e organização da operação da clínica.", access: ["Agenda e cadastros", "Pacotes e assinaturas", "Governança operacional"] },
  FINANCE: { name: "Paula Reis", initials: "PR", summary: "Acesso ao ciclo financeiro e fiscal sem expor conteúdo clínico.", access: ["Recebíveis, pagamentos e conciliação", "Fiscal e NFS-e", "Prontuários clínicos indisponíveis"] },
};

export function ProfilePage() {
  const { session } = useAuth();
  const [active, setActive] = useState<"profile" | "security" | "sessions">("profile");
  const [previewRole, setPreviewRole] = useState<UserRole>(session?.user.role ?? "OWNER");
  const toast = useToast();
  const demoMode = import.meta.env.DEV && import.meta.env.VITE_DEMO_MODE === "true";
  const sessions = useQuery({ queryKey: ["user-sessions"], queryFn: () => apiClient.request<Array<{ id: string; deviceLabel: string; createdAt: string; lastSeenAt: string; lastIp?: string; current: boolean }>>("/auth/sessions"), enabled: !demoMode });
  const revoke = useMutation({ mutationFn: (id: string) => apiClient.request<void>(`/auth/sessions/${id}`, { method: "DELETE" }), onSuccess: () => { void sessions.refetch(); toast("Sessão revogada com sucesso."); } });
  const revokeOthers = () => { (sessions.data ?? []).filter((item) => !item.current).forEach((item) => revoke.mutate(item.id)); };
  if (!session) return null;

  const preview = demoProfiles[previewRole];
  const tabClass = (tab: typeof active) => "flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm font-bold " + (active === tab ? "bg-harbor-50 text-harbor-700 dark:bg-harbor-950/40 dark:text-harbor-200" : "text-slate-500 dark:text-slate-400");
  return <div>
    <PageHeader eyebrow="Minha conta" title="Perfil e segurança" description="Dados da conta, segundo fator e sessões ativas." />
    <div className="grid gap-6 lg:grid-cols-[230px_1fr]">
      <Card className="h-fit p-2"><button type="button" onClick={() => setActive("profile")} aria-current={active === "profile" ? "page" : undefined} className={tabClass("profile")}><UserRound size={16} /> Perfil</button><button type="button" onClick={() => setActive("security")} aria-current={active === "security" ? "page" : undefined} className={tabClass("security")}><ShieldCheck size={16} /> Segurança</button><button type="button" onClick={() => setActive("sessions")} aria-current={active === "sessions" ? "page" : undefined} className={tabClass("sessions")}><Laptop2 size={16} /> Sessões</button></Card>
      <Card className="p-6">
        {active === "profile" && <div><div className="flex items-center gap-4"><span className="grid h-16 w-16 place-items-center rounded-3xl bg-harbor-100 font-display text-2xl font-extrabold text-harbor-700 dark:bg-harbor-900 dark:text-harbor-200">{session.user.initials}</span><div><h2 className="font-display text-xl font-extrabold text-ink dark:text-white">{session.user.name}</h2><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">{roleLabels[session.user.role]} · {session.user.tenant.name}</p></div></div><div className="mt-7 grid gap-4 sm:grid-cols-2"><Input label="Nome" defaultValue={session.user.name} disabled={!demoMode} /><Input label="E-mail" defaultValue={maskContact(session.user.email)} disabled /></div><Button className="mt-5" disabled={!demoMode} onClick={() => toast("Perfil atualizado no cenário demonstrativo.")}>{demoMode ? "Salvar demonstração" : "Edição de perfil indisponível"}</Button>
          <Card className={"mt-8 border-harbor-200 bg-harbor-50/40 p-5 dark:border-harbor-900 dark:bg-harbor-950/20 " + (!demoMode ? "hidden" : "")}><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex items-center gap-2"><h2 className="font-display text-lg font-bold text-ink dark:text-white">Troca de perfil para demonstração</h2><Badge tone="blue">Simulação</Badge></div><p className="mt-1 max-w-2xl text-sm leading-6 text-slate-500 dark:text-slate-400">Mostre como o produto separa os acessos por função. Esta prévia não altera a sessão atual nem concede permissões reais.</p></div><ShieldCheck className="hidden shrink-0 text-harbor-700 sm:block" size={22} /></div><div className="mt-5 grid gap-2 sm:grid-cols-2 xl:grid-cols-4">{(Object.keys(demoProfiles) as UserRole[]).map((role) => <button key={role} type="button" onClick={() => { setPreviewRole(role); toast("Perfil simulado: " + roleLabels[role] + "."); }} className={"rounded-xl border p-3 text-left transition " + (previewRole === role ? "border-harbor-500 bg-white shadow-sm dark:border-harbor-600 dark:bg-slate-900" : "border-harbor-100 bg-white/60 hover:border-harbor-300 dark:border-harbor-900 dark:bg-slate-900/40")}><span className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-lg bg-harbor-100 text-xs font-bold text-harbor-700 dark:bg-harbor-900 dark:text-harbor-200">{demoProfiles[role].initials}</span><span><span className="block text-sm font-bold text-ink dark:text-white">{roleLabels[role]}</span><span className="block text-xs text-slate-500 dark:text-slate-400">{demoProfiles[role].name}</span></span></span></button>)}</div><div className="mt-4 rounded-xl border border-harbor-100 bg-white p-4 dark:border-harbor-900 dark:bg-slate-900"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="text-xs font-semibold text-harbor-700 dark:text-harbor-300">Prévia ativa</p><p className="mt-1 font-display text-lg font-bold text-ink dark:text-white">{preview.name} · {roleLabels[previewRole]}</p></div><Badge tone="green">Acesso contextual</Badge></div><p className="mt-2 text-sm text-slate-500 dark:text-slate-400">{preview.summary}</p><div className="mt-4 grid gap-2 sm:grid-cols-3">{preview.access.map((item) => <div key={item} className="rounded-lg bg-harbor-50 px-3 py-2 text-xs font-semibold text-harbor-800 dark:bg-harbor-950/40 dark:text-harbor-200">{item}</div>)}</div></div></Card>
        </div>}
        {active === "security" && <div><ProfileTitle icon={<LockKeyhole />} title="Segurança da conta" description="MFA ativo e credenciais protegidas." /><div className="mt-6 space-y-4"><Notice title="MFA habilitado" tone="success">Sua conta exige segundo fator para entrar. A recuperação deve ser feita com códigos de uso único.</Notice><div className="flex items-center justify-between rounded-2xl border border-slate-100 p-4 dark:border-slate-800"><div><p className="text-sm font-bold text-ink dark:text-white">Aplicativo autenticador</p><p className="mt-1 text-xs text-slate-500 dark:text-slate-400">Configurado em 14 ago 2026 · último uso há 2 min</p></div><StatusBadge value="ACTIVE" /></div><Button variant="secondary" onClick={() => toast("Fluxo de rotação de MFA iniciado.")}><ShieldCheck size={15} /> Reconfigurar MFA</Button></div></div>}
        {active === "sessions" && <div><ProfileTitle icon={<Laptop2 />} title="Sessões ativas" description="Revogue acessos que você não reconhece." />{demoMode ? <div className="mt-6 space-y-3"><Session name="Este dispositivo" description="Cenário demonstrativo" current /><Session name="Outro navegador" description="Sessão de exemplo" /></div> : sessions.isPending ? <div className="mt-6 space-y-3"><div className="h-16 animate-pulse rounded-2xl bg-slate-100 dark:bg-slate-800" /><div className="h-16 animate-pulse rounded-2xl bg-slate-100 dark:bg-slate-800" /></div> : sessions.isError ? <Notice title="Sessões indisponíveis" tone="warning">Não foi possível consultar as sessões ativas.</Notice> : <div className="mt-6 space-y-3">{(sessions.data ?? []).map((item) => <Session key={item.id} name={item.deviceLabel} description={`Último uso ${formatDateTime(item.lastSeenAt)}`} current={item.current} onRevoke={() => revoke.mutate(item.id)} />)}</div>}{!demoMode && <Button variant="danger" className="mt-5" disabled={revoke.isPending || !(sessions.data ?? []).some((item) => !item.current)} onClick={revokeOthers}><LogOut size={15} /> Revogar outras sessões</Button>}{demoMode && <Button variant="secondary" className="mt-5" onClick={() => toast("Sessões são simuladas somente neste ambiente.")}><LogOut size={15} /> Revogar outras sessões</Button>}</div>}
      </Card>
    </div>
  </div>;
}

function ProfileTitle({ icon, title, description }: { icon: ReactNode; title: string; description: string }) { return <div className="flex items-start gap-3"><div className="rounded-xl bg-harbor-50 p-2.5 text-harbor-700 dark:bg-harbor-950/40 dark:text-harbor-300">{icon}</div><div><h2 className="font-display text-lg font-bold text-ink dark:text-white">{title}</h2><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">{description}</p></div></div>; }
function Session({ name, description, current = false, onRevoke }: { name: string; description: string; current?: boolean; onRevoke?: () => void }) { return <div className="flex items-center justify-between rounded-2xl border border-slate-100 p-4 dark:border-slate-800"><div className="flex items-center gap-3"><Laptop2 className="text-slate-500 dark:text-slate-400" size={19} /><div><p className="text-sm font-bold text-ink dark:text-white">{name}</p><p className="mt-1 text-xs text-slate-500 dark:text-slate-400">{description}</p></div></div>{current ? <span className="text-xs font-bold text-emerald-600 dark:text-emerald-400">Atual</span> : <button type="button" onClick={onRevoke} className="text-xs font-bold text-red-600 dark:text-red-400 hover:underline">Revogar</button>}</div>; }
